version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_server
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "start"]

